### ISSUE TITLE
voive commands and voice response

### ISSUE THREAD

**Issue by andlo** [andlo/theia-ide-skill#15]
As Theia is running on a mycroft devie, there is posibility for voice interaction and responses.

But what could be good, fun or helpfull ?

Having Mycroft telling all errors from linting isnt that smat I think. 

But maybe stuff like:
"Open volume-skill in IDE" - opens the skilldir as a workspace
"Deactivate skill" makes a skill deactiveted, so we can work on it whitout mycroft keeps saying there is an error in XXX skill.

l

**Comment by andlo** [comment]
Added start, stop and restrt voice commands

**Comment by domcross** [comment]
Unfortunately this skill now reacts to "stop" utterance for stopping playback of skills (e.g. Pandora or Spotify). I was working on the stop() function of one of my own skills and while testing Theia IDE shut down. Can you change stop to "deactivate" or "shut down"?

**Comment by andlo** [comment]
Oh That is not intended. You are right - I will change sart and stop to activate and shut down.
