### ISSUE TITLE
do not want to start

### ISSUE THREAD

**Issue by gras64** [andlo/theia-ide-skill#3]
warning @theia/cli > @theia/application-manager > less > request > hawk > cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > cryptiles > boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > boom > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > less > request > hawk > sntp > hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
~~~~> @theia/application-manager > webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update
~~~~ion-manager > webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update
~~~~ng @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
~~~~> @theia/application-manager > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
........
error An unexpected error occurred: "https://registry.yarnpkg.com/@theia/core/-/core-0.3.16.tgz: ESOCKETTIMEDOUT".
........
error Command "theia" not found.
12:20:45.133 - TheiaIde - INFO - THEIA IDE is installed and configured
12:20:45.134 - TheiaIde - INFO - Starting THEIA IDE
12:20:45.175 - mycroft.skills.core:load_skill:145 - INFO - Loaded theia-ide-skill.andlo
12:20:45.182 - mycroft.skills.core:load_skill:149 - INFO - First run of theia-ide-skill.andlo
..........
yarn run v1.12.3
error Command "theia" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by andlo** [comment]
The skill hassnt any good errorhandling :( Thats why it says THEIA is installed, but isnt as the loglines before that says.

Did you make more swap? to do that ssh into your device and do:
```
sudo nano /etc/dphys-swapfile
```
exit by Ctrl+X and save And restart swarpfile
```
sudo /etc/init.d/dphys-swapfile stop
sudo /etc/init.d/dphys-swapfile start
```

Whitout enough memmory the install fails.

You could change swapsize and remove the skill and install again (or you could delete settings.json in skills dir and restart skillsservice.
